server {
    listen 80;
    server_name maiatechsolution.com.br www.maiatechsolution.com.br;
    
    # Joga todo tráfego HTTP normal para o HTTPS seguro
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name maiatechsolution.com.br www.maiatechsolution.com.br;

    index index.php index.html;
    root /var/www/public;

    # Caminhos dos certificados SSL gerados pelo Certbot (Lidos de dentro do container)
    ssl_certificate /etc/letsencrypt/live/maiatechsolution.com.br/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/maiatechsolution.com.br/privkey.pem;

    ssl_protocols TLSv1.2 TLSv1.3;
    ssl_ciphers HIGH:!aNULL:!MD5;

    error_log  /var/log/nginx/error.log;
    access_log /var/log/nginx/access.log;

    location ~ \.php$ {
        try_files $uri =404;
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        fastcgi_pass app:9000;
        fastcgi_index index.php;
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
        gzip_static on;
    }
}